### ISSUE TITLE
Codacy coverage fails if called by dependabot[bot].

### ISSUE THREAD

**Issue by terjekv** [terjekv/hubuum#130]
See https://github.com/terjekv/hubuum/actions/runs/4916029000/jobs/8779405265#step:7:94 as an example. The solution may be to do something like:

```yaml
codacy:
  name: Codacy coverage
  runs-on: ubuntu-latest
  needs: coveralls
  if: github.actor != 'dependabot[bot]'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download coverage
      uses: actions/download-artifact@v3
      with:
        name: coverage-3.10
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
    - name: Convert coverage
      run: coverage xml
    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
```
