### ISSUE TITLE
Add GitHub actions to dependabot

### ISSUE THREAD

**Issue by terjekv** [terjekv/hubuum#56]
Something like this?

````yaml
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

````
